apiVersion: executor.kubtest.io/v1
kind: Executor
metadata:
  annotations:
    meta.helm.sh/release-name: kubtest
    meta.helm.sh/release-namespace: default
  name: curl-executor
spec:
  executor_type: rest
  types:
  - curl/test
  uri: http://kubtest-curl-executor:8086
