site_name: kubtest
site_description: 'Your Kubernetes Testing Friend'
site_author: 'Kubeshop kubtest Team'
docs_dir: docs/
repo_name: 'kubeshop/kubtest'
repo_url: 'https://github.com/kubeshop/kubtest'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - go

nav:
  - Welcome: index.md
  - Installation: installing.md
  - Usage: getting-started.md
  - Reference: reference.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Development: development.md

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>

