on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push api-server
        id: docker_build_api_server
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.vars.outputs.tag }}
          file: build/api-server/Dockerfile
      -
        name: Build and push postman-executor
        id: docker_build_postman_executor
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.vars.outputs.tag }}
          file: build/postman-executor/Dockerfile