name: Release Charts

on:
  push:
    branches:
      - main
  pull_request: # To be removed once confirmed to be working. For testing purposes only.
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser for api-server chart
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts/api-server
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser for postman-executor chart
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts/postman-executor
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser for kubetest chart
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts/kubetest
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"