name: Release Postman Executor chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/postman-executor/**'

jobs:

  release_postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts/postman-executor
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"