name: Release Charts

on:
  push:
    # branches:
    #   - main
    paths:
      - 'charts/kubetest/**'
  # workflow_run:
  #   workflows: ["Release Api Server chart","Release Postman Executor chart"]
  #   # branches: [main]
  #   types: 
  #     - completed

jobs:

  release_kubetest:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts/kubetest
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"