name: Release Kubetest CLI for Kubectl.

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  generate:
    name: Create and upload release-artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Kubetest CLI ${{ github.ref }}
          body: |
            Changes in this Release
            - Releasing new version of the Kubetest CLI for Kubectl.
          draft: false
          prerelease: false

      - name: Generate the artifacts
        uses: skx/github-action-build@master
        with:
          builder: .github/kubectl-kubetest-builder

      - name: Upload the artifacts to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: 'kubectl-kubetest'